version: '3.8'

services:
  api:
    build: .
    container_name: fullcontrol-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Agrega tus variables de entorno aqu√≠
      - DB_HOST=192.168.1.22
      - DB_USER=mini-pc
      - DB_PASSWORD=Admin123!
      - DB_NAME=fullcontrol
      - DB_PORT=3307
      - SERVER_URL=http://192.168.1.22:3000
    volumes:
      # Persistir uploads fuera del contenedor
      - ./uploads:/app/uploads
      # Para desarrollo: hot-reload habilitado
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - fullcontrol-network

networks:
  fullcontrol-network:
    driver: bridge

# volumes:
#   db-data: